AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-template

  Sample SAM Template for sam-template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Runtime: python3.8
    Environment:
      Variables:
        ENV: !Ref Env
        ENDPOINT: !FindInMap [ EnvMap, !Ref Env, Endpoint ]
        SLACK_POST_URL: !Ref SlackPostUrl
        SLACK_CHANNEL: !Ref SlackChannel
        SLACK_TOKEN: !Ref SlackToken

Parameters:
  Env:
    Type: String
    AllowedValues:
      - prod
      - stg
      - dev
      - local
    Default: dev
  SlackPostUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /sample/notification/slack/url
  SlackChannel:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /sample/notification/slack/channel
  SlackToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /sample/notification/slack/token

Mappings:
  EnvMap:
    prod:
      Endpoint: ''
    stg:
      Endpoint: ''
    dev:
      Endpoint: ''
    local:
      Endpoint: 'http://host.docker.internal:4566'


Resources:

  slackNotificationAwscostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: slack-notification-awscost/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - CloudWatchReadOnlyAccess


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  slackNotificationAwscostFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt slackNotificationAwscostFunction.Arn

